dialogue_list = [
    "Mere paas maa hai.",
    "Kitne aadmi the?",
    "Rahul, naam toh suna hoga.",
    "Don ko pakadna mushkil hi nahin, namumkin hai.",
    "Aaj ek hasi aur baant lo, aaj ek dua aur maang lo, aaj ek ansoo aur pee lo, aaj ek zindagi aur jee lo, aaj ek sapna aur dekh lo, aaj... kya pata, kal ho na ho!",
    "Bade bade deshon mein aisi chhoti chhoti baatein hoti rehti hai, Senorita.",
    "Aapko shikayat ka mauka nahi milega.",
    "Kabhi kabhi kuch jeetne ke liye kuch haarna bhi padta hai, aur haar kar jeetne wale ko baazigar kehte hain.",
    "Mogambo khush hua.",
    "Tareekh pe tareekh, tareekh pe tareekh milti gayi My Lord, par insaaf nahi mila.",
    "Bhagwan ke bharose na baithiye, kya pata bhagwan hamare bharose baitha ho.",
    "Kya tum maut ko dhoka bol rahe ho?",
    "Moochein ho toh Nathulal jaisi ho warna na ho.",
    "Rishte mein toh hum tumhare baap lagte hain, naam hai Shahenshah.",
    "Aap purush hi nahi, mahapurush hain.",
    "Tum ek bade wale dacoit ho Gabbbar.",
    "Mera naam Suraj Pratap hai, bhaigiri mein PhD hai.",
    "Aapne mere bete ko chuna lagaya.",
    "Don ko 11 mulkon ki police dundh rahi hai, lekin ek gyarah bheje ka bhi pata nahin laga.",
    "Mai udna chahta hoon, daudna chahta hoon, girna bhi chahta hoon ... bus rukna nahi chahta.",
    "Hum jahan khade hote hain, line wahi se shuru hoti hai.",
    "Pushpa I hate tears.",
    "Aaj ek hasi aur baant lo aaj ek dua aur maang lo, aaj ek ansoo aur pee lo, aaj ek zindagi aur jee lo, aaj ek sapna aur dekh lo, aaj... kya pata, kal ho na ho!",
    "Bade bade deshon mein aisi chhoti chhoti baatein hoti rehti hai, Senorita.",
    "Aapko shikayat ka mauka nahi milega.",
    "Kabhi kabhi kuch jeetne ke liye kuch haarna bhi padta hai, aur haar kar jeetne wale ko baazigar kehte hain.",
    "Mogambo khush hua.",
    "Tareekh pe tareekh, tareekh pe tareekh milti gayi My Lord, par insaaf nahi mila.",
    "Bhagwan ke bharose na baithiye, kya pata bhagwan hamare bharose baitha ho.",
    "Kya tum maut ko dhoka bol rahe ho?",
    "Moochein ho toh Nathulal jaisi ho warna na ho.",
    "Rishte mein toh hum tumhare baap lagte hain, naam hai Shahenshah.",
    "Aap purush hi nahi, mahapurush hain.",
    "Tum ek bade wale dacoit ho Gabbbar.",
    "Mera naam Suraj Pratap hai, bhaigiri mein PhD hai.",
    "Aapne mere bete ko chuna lagaya.",
    "Don ko 11 mulkon ki police dundh rahi hai, lekin ek gyarah bheje ka bhi pata nahin laga.",
    "Mai udna chahta hoon, daudna chahta hoon, girna bhi chahta hoon ... bus rukna nahi chahta.",
    "Hum jahan khade hote hain, line wahi se shuru hoti hai.",
    "Yeh duniya ek third class ka dibba hai, aur hum usmein first class ke passengers hain.",
    "Zindagi mein kuch banna ho, kuch haasil karna ho, kuch jeetna ho toh hamesha apne dil ki suno.",
    "Hum ek baar jeete hain, ek baar marte hain, shaadi bhi ek hi baar hoti hai, aur pyar... ek hi baar hota hai.",
    "Joh khud apni khatir jeete hain, woh doosron ke liye marte hain.",
    "Dimaag aur dil mein zameen asman ka farak hota hai.",
    "Bade bade deshon mein aisi chhoti chhoti baatein hoti rehti hai, Senorita.",
    "Zindagi ka tambu teen bambuon pe khada hota hai - ek bambu uspe khada hota hai joh humne khud banaya hota hai, doosra bambu uspe khada hota hai joh humare maa baap ne banaya hota hai, aur teesra bambu uspe khada hota hai joh Bhagwan ne banaya hota hai.",
    "Ek ladki thi deewani si, deewani si.",
    "Naam, bade aur ghar, chhote... sab kuch hai.",
    "Aaj mere paas gaadi hai, bungla hai, paisa hai... tumhare paas kya hai?",
    "Joh darr gaya, samjho marr gaya.",
    "Yeh duniya ek circus hai, aur hum is circus ke us paar wale tamasha dekhne aaye hain.",
    "Hum tum mein itne ched karenge ki confuse ho jaoge ki saans kahan se le aur paadein kahan se.",
    "Hum jahan khade hote hain, line wahi se shuru hoti hai.",
    "Jab tak ek mard ko apni aurat ka sir nahi jhukta, woh mard nahi hota.",
    "Dil mein aata hoon, samajh mein nahi.",
    "Sara shehar mujhe lion ke naam se jaanta hai.",
    "Ghar mein mummy papa hote hain, toh sirf ek hi jagah ladai hoti hai - bathroom mein.",
    "Yeh ek bhari duniya hai, ek time pass aur doosri ek struggle.",
    "Zindagi mein teen cheez kabhi underestimate nahi karna chahiye - I, me and myself.",
    "Jo tera torture hai, woh mera warm-up hai.",
    "Dil toh har kisi ke paas hota hai, lekin sab dilwale nahi hote.",
    "Bade bade deshon mein aisi chhoti chhoti baatein hoti rehti hai, Senorita.",
    "Zindagi ka tambu teen bambuon pe khada hota hai - ek bambu uspe khada hota hai joh humne khud banaya hota hai, doosra bambu uspe khada hota hai joh humare maa baap ne banaya hota hai, aur teesra bambu uspe khada hota hai joh Bhagwan ne banaya hota hai.",
    "Ek ladki thi deewani si, deewani si.",
    "Naam, bade aur ghar, chhote... sab kuch hai.",
    "Aaj mere paas gaadi hai, bungla hai, paisa hai... tumhare paas kya hai?",
    "Joh darr gaya, samjho marr gaya.",
    "Yeh duniya ek circus hai, aur hum is circus ke us paar wale tamasha dekhne aaye hain.",
    "Hum tum mein itne ched karenge ki confuse ho jaoge ki saans kahan se le aur paadein kahan se.",
    "Hum jahan khade hote hain, line wahi se shuru hoti hai.",
    "Jab tak ek mard ko apni aurat ka sir nahi jhukta, woh mard nahi hota.",
    "Dil mein aata hoon, samajh mein nahi.",
    "Sara shehar mujhe lion ke naam se jaanta hai.",
    "Ghar mein mummy papa hote hain, toh sirf ek hi jagah ladai hoti hai - bathroom mein.",
    "Yeh ek bhari duniya hai, ek time pass aur doosri ek struggle.",
    "Zindagi mein teen cheez kabhi underestimate nahi karna chahiye - I, me and myself.",
    "Jo tera torture hai, woh mera warm-up hai.",
    "Dil toh har kisi ke paas hota hai, lekin sab dilwale nahi hote."
]

