jokes_list = [
    "Teacher: Tumhara homework kyun nahi kiya? \nStudent: Madam, ghar pe bijli nahi thi, isliye bulb nahi jala paaye.",
    "Ek chor police se chupne ke liye ek khokhe mein chala gaya. \nChor: Yahan kyun aa gaya? \nKhokha Wala: Koi kya ukhaad lega yahan, yeh toh police wala khokha hai!",
    "Wife: Tum mere liye kya laaye ho Valentine's Day par? \nHusband: Tumhe tension free dekhne ke liye empty wallet laaya hoon.",
    "Santa: Tu har exam mein fail kyun hota hai? \nBanta: Kyunki pass ho jaun toh next class mein jaana padega, wahan bhi main hi fail ho jaunga!",
    "Biwi: Tum har waqt mujhe ghoorte kyun rehte ho? \nPati: Main tujhe kya kahu, meri shakal hi aisi hai ki kuch bhi padhne layak nahi dikhta!",
    "Dost: Tere phone mein toh bahut saare sad song hain, kyun? \nMain: Taki jab koi mujhe disturb kare, main use suna saku ki main kitna udas hoon!",
    "Pappu: Papa, meri girlfriend ko birthday gift dena hai, kya doon? \nPapa: Beta, ek saal ka gym membership de de, shayad uska kuch fayda ho!",
    "Wife: Tum dinner ke liye kyun nahi aaye? \nHusband: Main bhi kya bolu, khushi mein rehna allowed nahi hai!",
    "Bunty: Tumhare paas girlfriend hai, mujhe bhi chahiye. \nMunna: Kya kar lega uske saath? \nBunty: Main use confuse kar doonga, phir confuse hi sahi!",
    "Santa: Main kyun ro raha hoon, tu bata. \nBanta: Kyunki tune alarm clock bajaya tha, ab ro mat!",
    "Teacher: Kal tum absent kyun the? \nStudent: Madam, mujhe kal bukhar tha. \nTeacher: Lekin aaj toh theek lag rahe ho. \nStudent: Madam, aaj bukhar ka baari aaya hai.",
    "Biwi: Tum mere liye kuch kyun nahi likhte? \nPatni: Maine toh shaadi ke samay hi likh diya tha, ab aur kya likhu?",
    "Ladka: Tumhare chehre pe ek noor sa dikhta hai. \nLadki: Woh mera noor nahi, tera bill hai!",
    "Pappu: Yaar, woh dekh, mere dil ka dard khushi se bhara hua hai. \nBunty: Woh kya hai? \nPappu: Credit card ka bill aaya hai!",
    "Boss: Tum late kyun aaye ho kaam par? \nEmployee: Sir, aaj alarm clock ne bhi thoda overacting kar liya!",
    "Santa: Tumne itne saare gifts kyun bheje hain? \nBanta: Arre, online shopping karte waqt 'Cash on Delivery' select kiya tha!",
    "Wife: Tum mujhe kitna pyaar karte ho? \nHusband: Kitna pyaar karti ho tum? \nWife: Main toh tumhe chaand tak le aungi. \nHusband: Toh le aao, main bhi dharti tak le aata hoon!",
    "Santa: Tumhein yaad hai, tumne mujhe kya diya tha birthday par? \nBanta: Haan yaar, maine toh tujhe dekha bhi nahi tha woh din!",
    "Ladka: Tumhari aankhon mein ek baat chhupi hui hai. \nLadki: Kya? \nLadka: Chashma!",
    "Pati: Tum har waqt shopping karne jaati ho. \nPatni: Kya karu, main bhi 'window shopping' pe gayi thi, wahan se aa gayi!",
    "Teacher: Tum apne homework kyun nahi kiye? \nStudent: Aapne toh ghar par bhej diya hi nahi!",
    "Bunty: Tere gaal kyun laal laal hain? \nMunna: Kya karu, Santa ne kaha tha ki agar face book par 'like' nahi kiya toh gaal laal ho jaayenge!",
    "Santa: Kya tum mujhe bhool jaogi? \nBanta: Arre nahi yaar, main tujhe kabhi bhoolunga nahi. \nSanta: Thank you yaar, teri galati nahi hoti!",
    "Biwi: Tumne mere liye kuch naya socha hai? \nPati: Haan, ek naya hairstyle socha hai, tum try karo!",
    "Santa: Kya tum mujhe yaad karogi, jab main Delhi chala jaunga? \nBanta: Yaar, tu Delhi ja raha hai ya chhod raha hai, thoda clear kar!",
    "Wife: Tum mujhe kitna pyaar karte ho? \nHusband: Jitna aaj tak koi pati nahi kiya hoga, warna tu toh pehle hi ghar se bhaag jaati!",
    "Pappu: Tere ghar mein sabse intelligent kaun hai? \nBunty: Mera kutta. \nPappu: Kya? Woh kaise? \nBunty: Kyunki har exam mein usse pass karwa deta hoon!",
    "Santa: Main ek din bada aadmi banunga. \nBanta: Woh toh theek hai, lekin kisi din tera bada aadmi banne ka din kab aayega, yeh toh decide kar le!",
    "Teacher: Agar koi ladka kisi ladki ko propose kare aur ladki na kahe toh kya kahenge? \nStudent: Yeh toh sadma hoga!",
    "Biwi: Tumne mujhe birthday gift kyun nahi diya? \nPati: Arre, maine toh tumhe woh cute teddy bear diya tha na, usi mein teri tarah kuch bolne wala nahi tha!",
    "Santa: Tumhari girlfriend ko kyun chhupa ke rakha hai? \nBanta: Kyunki uske husband ko nahi pata ki woh meri girlfriend hai!",
    "Pappu: Tere ghar ke saamne ka jo kutta bhonkta hai, woh teri kyun marta hai? \nBunty: Woh mere girlfriend ka kutta hai, jo mujhe dekh ke bhonkta hai!",
    "Santa: Tumhara beta kyun ro raha hai? \nBanta: Kyunki maine usse bola hai ki 'School se bhaag ja, tujhe kuch nahi sikha sakte woh log!'",
    "Teacher: Tumhare papa kya karte hain? \nPappu: Woh karte hi kya hain, madam, woh apne kaam se hi ghar late aate hain!",
    "Santa: Tumhare bina mere jeene ki koi soorat nahi hai. \nBanta: Toh phir mujhe jeene kyun nahi deta?",
    "Wife: Tum mere liye kuch special banate kyun nahi ho? \nHusband: Kyunki maine tumhe hi toh special banaya tha!",
    "Santa: Tumne kyun naya phone kharida? \nBanta: Kyunki mere paas paise kam the, isliye ek naya tarika dhundha!",
    "Biwi: Tum mujhe kabhi bhi gift kyun nahi dete? \nPati: Arre, maine toh tumhe apni zindagi di hai, woh kya kam hai?",
    "Pappu: Tumhare ghar mein kitni languages mein baat hoti hai? \nBunty: Do. Ek woh jo hum samajh nahi paate, aur doosri woh jo humein samajh nahi aati!",
    "Santa: Main tumhe ghar chhod doon? \nBanta: Nahi yaar, mujhe pehle hi bahut log ghar chhod chuke hain, ab aur mat chhod!",
    "Wife: Tum jab se naye phone le aaye ho, tab se mere liye time nahi nikalte. \nHusband: Arre, maine toh teri photo hi set nahi ki hai, time kaise nikalu?",
    "Santa: Tumhare haath mein aisa kya hai jo mujhe nahi hai? \nBanta: Mere haath mein teri maut ka asar hai!",
    "Pappu: Main kyun jeena chahta hoon? \nBunty: Tera koi choice nahi hai, tune mere saath contract sign kiya hai!",
    "Santa: Tumhare toh bade bade sapne hain. \nBanta: Haan, main bhi filmo mein hero banne ka soch raha hoon. \nSanta: Arre, tu toh comedy mein hi hero ban gaya hai!",
    "Biwi: Tum toh har baat pe gussa ho jaate ho. \nPati: Nahi, main toh bahut cool hoon. \nBiwi: Arre, yeh cooler mein kyun baitha hai fir?",
    "Santa: Yeh kaisi car hai, steering wheel bhi nahi hai. \nBanta: Arre, automatic car hai, chalti hai apne aap!",
    "Wife: Tumhare saath rehne se accha main single hi theek thi. \nHusband: Toh phir single hi ban ja, main bhi koi rokne waala nahi hoon!",
    "Pappu: Tumhare teeth kitne sundar hain. \nBunty: Arre, thanks yaar, inki toh main bhi fan hoon!",
    "Santa: Tumne toh aajkal gym join kiya hua hai. \nBanta: Haan, woh doctor ne kaha tha, 'no pain, no gain'. \nSanta: Arre, woh toh mera motto bhi hai, lekin woh pain mujhe wife se aata hai!",
    "Pappu: Tumhare ghar mein sab kuch kyun ganda hota hai? \nBunty: Kyunki mere ghar mein koi bhi detergent ka ad nahi shoot karta!",
    "Biwi: Tum har waqt mujhe shopping karne kyun bhejte ho? \nPati: Kyunki main nahi ja sakta, woh security guard mujhe jaane nahi deta!",
    "Santa: Tumne naya mobile kyun liya? \nBanta: Kyunki mera purana mobile mujhe 'outdated' feel karata tha!",
    "Pappu: Tumne mujhe kyun nahi bataya ki tum doctor ho? \nBunty: Kyunki main bhi nahi jaanta tha, woh nurse mujhe batati rahi!",
    "Santa: Tumhare ghar mein itni saari paintings kyun hain? \nBanta: Kyunki mujhe laga, agar koi chor aaye toh woh confuse ho jayega ki konsi original hai!",
    "पति: जानु तुम चाय बना रही हो ना?\nपत्नी: हां बना रही हूँ.\nपति: अच्छा, तो मेरे लिए भी एक पेट बना दो 🍲",
    "टीचर: बच्चों, तुम्हें अपनी जिंदगी में एक बड़ा आदमी बनना है।\nबच्चा: मैडम, बड़ा बनने के बाद अगर आपसे मिलना हुआ तो कौन बड़ा होगा? 😄",
    "पति: तुम्हारी खूबसूरती ने मेरे दिल को चुराया है।\nपत्नी: तो तुम्हें वापस कर दूं क्या? 😜",
    "संता: यार, इस बार की लड़ाई तो मैं हार गया, बीवी ने कहा, 'बहुत हो गया, अब बारी बारी से सोना!'\nबंता: ओ भाई, तू तो जीत गया, अब तो बारी-बारी से सोना है! 😂",
    "पति: तुम्हारी बेहेन बच्चों के साथ बहुत अच्छी है, क्या तुम भी ऐसी बन सकती हो?\nपत्नी: हां, मैं भी ऐसी ही बन सकती हूँ, मगर तू बच्चा कहाँ से लाऊगा? 😁",
    "संता: बॉस, मेरी वाइफ बहुत अच्छी छुपाई जाती है।\nबॉस: वाह, तुम्हारी बीवी कौन सी फिल्म में है?\nसंता: फिर हंसी आ गई, वो कोई फिल्म नहीं देखती! 🤭",
    "पति: तुम्हारी दोस्त मेरे सपने में क्या देख रही थी?\nपत्नी: उसका भी तो सपना था कि वह तुम्हारा पति है! 😂",
    "संता: तू इतना क्यों हंस रहा है?\nबंता: कुछ नहीं, बस वक्त के साथ साथ मेरे बाल भी उड़ रहे हैं! 😅",
    "पति: क्या तुम शादी से पहले मुझे बहुत याद करती थी?\nपत्नी: हां, पर तब मुझे तुमसे शादी की उम्मीद नहीं थी! 🤣",
    "संता: तेरे लिए एक गाना गाऊं?\nबंता: नहीं, मुझे नहीं सुनना!\nसंता: अबे वो तो बात ही अलग है, मैं तो तेरे लिए ही गाऊंगा! 😂",
]
