love_shayari = [
    "Tere ishq mein dooba rahe, teri baahon mein kho jaaun",
    "Mohabbat ki raahon mein aahista aahista kho jayein hum",
    "Tum meri zindagi mein ho, meri har khushi mein ho",
    "Dil ko chhune wale pal, teri muskurahat mein chhupi hai",
    "Tum mere dil ki duniya mein ho, mere khwabon mein ho",
    "Teri baaton mein chhupi hai wo mithas, jo dil ko bhaaye",
    "Tere ishq mein khud ko bhula diya, teri aankhon mein kho gaya",
    "Tumhare bina adhoori hai ye raatein, tum mere liye sab kuch ho",
    "Mohabbat hai teri, isliye dil se nahin, jaan se pyara lagta hai tu",
    "Har pal tere saath rehna chahta hoon, teri zindagi mein khush rehna chahta hoon",
    "Tumhari muskurahat meri zindagi bana deti hai, tumse pyaar karna meri adat ban gayi hai",
    "Tum mere liye roshni ho, meri har andheri raat mein",
    "Teri baaton mein chhupi hai wo baat, jo dil ko choo jaaye",
    "Teri muskurahat meri zindagi ko roshan karti hai",
    "Tum mere dil ka sukoon ho, meri har khushi ho tum",
    "Tumse juda hokar bhi, tumse juda nahi lagta",
    "Tumhare bina meri duniya adhoori hai, tum meri poori kahani ho",
    "Meri har saans mein tum ho, meri har dastaan mein tum ho",
    "Teri har muskurahat meri zindagi ko khushiyon se bhar deti hai",
    "Tum mere liye kuch khaas ho, tumse juda hokar bhi tum mere paas ho",
    "Tere bina zindagi adhoori hai, tum meri zindagi ka maksad ho",
    "Teri muskurahat meri zindagi ka sabse pyaara lamha hai",
    "Tumhari har baat meri zindagi mein rang bhar deti hai",
    "Tere ishq mein kho jana meri aadat ban gayi hai",
    "Tum meri har khushi ho, tum meri har zarurat ho",
    "Teri baaton mein chhupi hai meri har khushi",
    "Tum meri zindagi ka sabse khoobsurat sapna ho",
    "Teri aankhon mein dooba raha, teri baaton mein kho gaya",
    "Tum mere liye sab kuch ho, tumse juda hokar bhi tum mere dil mein ho",
    "Tum meri zindagi mein ho, meri har khushi mein ho",
    "Tumhare bina meri zindagi adhoori hai, tum meri poori kahani ho",
    "Tere ishq mein dooba rahe, teri baahon mein kho jaaun",
    "Mohabbat ki raahon mein aahista aahista kho jayein hum",
    "Tum meri har khushi ho, tum meri har zarurat ho",
    "Teri muskurahat meri zindagi ka sabse pyaara lamha hai",
    "Tum meri zindagi ka sabse khoobsurat sapna ho",
    "Tum mere dil ka sukoon ho, meri har khushi ho tum",
    "Tere bina meri duniya adhoori hai, tum meri zindagi ka maksad ho",
    "Tumse juda hokar bhi, tumse juda nahi lagta",
    "Tum meri har khushi ho, tum meri har zarurat ho",
    "Teri baaton mein chhupi hai meri har khushi",
    "Tum meri zindagi mein ho, meri har khushi mein ho",
    "Tumhare bina meri zindagi adhoori hai, tum meri poori kahani ho",
    "Tere ishq mein dooba rahe, teri baahon mein kho jaaun",
    "Mohabbat ki raahon mein aahista aahista kho jayein hum",
    "Tum meri har khushi ho, tum meri har zarurat ho",
    "Teri muskurahat meri zindagi ka sabse pyaara lamha hai",
    "Tum meri zindagi ka sabse khoobsurat sapna ho",
    "Tum mere dil ka sukoon ho, meri har khushi ho tum",
    "Tere bina meri duniya adhoori hai, tum meri zindagi ka maksad ho",
    "Tumse juda hokar bhi, tumse juda nahi lagta",
    "Tum meri har khushi ho, tum meri har zarurat ho",
    "Teri baaton mein chhupi hai meri har khushi",
    "Tum meri zindagi mein ho, meri har khushi mein ho",
    "Tumhare bina meri zindagi adhoori hai, tum meri poori kahani ho",
    "Tere ishq mein dooba rahe, teri baahon mein kho jaaun",
    "Mohabbat ki raahon mein aahista aahista kho jayein hum",
]
