shayari_list = [
    "Dil ko behlaye, aankhon ko rulaye, yeh ishq nahi toh phir aur kya kahain?",
    "Tere ishq mein khud ko bhula diya, tere pyaar mein kuch khaas hai.",
    "Raat bhar teri yaadon mein khoya, dil se dil juda na ho paya.",
    "Mohabbat mein teri deewana ho gaya, tere ishq mein khud ko bhula diya.",
    "Dil se tera khayal na jaye, tere bina jeena mushkil ho jaye.",
    "Tere pyaar mein dard bhara hai, par tujhse juda ho jaana bhi impossible hai.",
    "Tere ishq mein dooba, teri yaadon mein khoya, main hoon tere bina adhoora.",
    "Teri muskan mein chhupi hai khushiyan, teri baaton mein basa hai pyara sa jahan.",
    "Dil ki duniya basa ke chhoda hai tu, tere bina kuch bhi mera nahi.",
    "Tere ishq mein hai rangon ka jahan, har pal hai ek kahani tere pyaar ki.",
    "Jab se juda hoke tujhse gaya hai, har pal lagta hai adhoora sa.",
    "Teri aankhon mein dooba ek pyara sa sapna, teri muskurahat mein basa hai mera armaan.",
    "Tere pyaar mein khoye hain hum, teri baaton mein basa hai dil ka sukoon.",
    "Dil ko hai teri zarurat, tere bina kuch bhi nahi hai khaas.",
    "Tere ishq mein hai rangon ka jahan, har pal hai ek kahani tere pyaar ki.",
    "Jab se juda hoke tujhse gaya hai, har pal lagta hai adhoora sa.",
    "Teri aankhon mein dooba ek pyara sa sapna, teri muskurahat mein basa hai mera armaan.",
    "Tere pyaar mein khoye hain hum, teri baaton mein basa hai dil ka sukoon.",
    "Dil ko hai teri zarurat, tere bina kuch bhi nahi hai khaas.",
    "Meri har khushi tere ishq mein hai, teri muskurahat se hai mera dil bharpoor.",
    "Teri baaton mein chhupi hai raaz-e-dil, teri aankhon mein basa hai pyara sa khwab.",
    "Tere ishq mein hai rangon ka jahan, har pal hai ek kahani tere pyaar ki.",
    "Jab se juda hoke tujhse gaya hai, har pal lagta hai adhoora sa.",
    "Teri aankhon mein dooba ek pyara sa sapna, teri muskurahat mein basa hai mera armaan.",
    "Tere pyaar mein khoye hain hum, teri baaton mein basa hai dil ka sukoon.",
    "Dil ko hai teri zarurat, tere bina kuch bhi nahi hai khaas.",
    "Meri har khushi tere ishq mein hai, teri muskurahat se hai mera dil bharpoor.",
    "Teri baaton mein chhupi hai raaz-e-dil, teri aankhon mein basa hai pyara sa khwab.",
    "Tere ishq mein hai rangon ka jahan, har pal hai ek kahani tere pyaar ki.",
    "Jab se juda hoke tujhse gaya hai, har pal lagta hai adhoora sa.",
    "Teri aankhon mein dooba ek pyara sa sapna, teri muskurahat mein basa hai mera armaan.",
    "Tere pyaar mein khoye hain hum, teri baaton mein basa hai dil ka sukoon.",
    "Dil ko hai teri zarurat, tere bina kuch bhi nahi hai khaas.",
    "Meri har khushi tere ishq mein hai, teri muskurahat se hai mera dil bharpoor.",
    "Teri baaton mein chhupi hai raaz-e-dil, teri aankhon mein basa hai pyara sa khwab.",
    "Tere ishq mein hai rangon ka jahan, har pal hai ek kahani tere pyaar ki.",
    "Jab se juda hoke tujhse gaya hai, har pal lagta hai adhoora sa.",
    "Teri aankhon mein dooba ek pyara sa sapna, teri muskurahat mein basa hai mera armaan.",
    "Tere pyaar mein khoye hain hum, teri baaton mein basa hai dil ka sukoon.",
    "Dil ko hai teri zarurat, tere bina kuch bhi nahi hai khaas.",
    "Meri har khushi tere ishq mein hai, teri muskurahat se hai mera dil bharpoor.",
    "Teri baaton mein chhupi hai raaz-e-dil, teri aankhon mein basa hai pyara sa khwab.",
    "Tere ishq mein hai rangon ka jahan, har pal hai ek kahani tere pyaar ki.",
    "Jab se juda hoke tujhse gaya hai, har pal lagta hai adhoora sa.",
    "Teri aankhon mein dooba ek pyara sa sapna, teri muskurahat mein basa hai mera armaan.",
    "Tere pyaar mein khoye hain hum, teri baaton mein basa hai dil ka sukoon.",
    "Dil ko hai teri zarurat, tere bina kuch bhi nahi hai khaas.",
]
