songs_lyrics = {
    "song1": "Tere bina jeena pade, toh zindagi kya zindagi",
    "song2": "Jeene laga hoon pehle se zyada, pehle se zyada tum pe marne laga hoon",
    "song3": "Sun saathiya mahiya, barsaat bhi aakar chali gayi",
    "song4": "Main phir bhi tumko chahunga, is chahat mein marr jaaunga",
    "song5": "Tum hi ho, ab tum hi ho, zindagi ab tum hi ho",
    "song6": "Aaj se teri saari galiyan meri ho gayi",
    "song7": "Tum jo aaye zindagi mein baat ban gayi",
    "song8": "Channa mereya mereya, channa mereya mereya",
    "song9": "Tere sang yaara, khush rang bahara",
    "song10": "Janam janam ka saath hai, nibhaane ko saath hai",
    "song11": "Raabta, kehte hain khuda ne",
    "song12": "Nazdeekiyan, mil ke yeh bhi woh bhi",
    "song13": "Sab tera, sab tera, sab tera phoolon se jyada phoolon se bhara",
    "song14": "Muskurane ki wajah tum ho, gungunane ki wajah tum ho",
    "song15": "Bolna mahi bolna, tere liye aaya main toh",
    "song16": "Tum mile toh lamhe tham gaye, tum mile toh saare karam",
    "song17": "Hasi ban gaye, tum mere aasmaan",
    "song18": "Kar gayi chull, mat kar itna ullu",
    "song19": "Zara sa, zara sa khwabon mein roz aao",
    "song20": "Gerua, rang de tu mohe gerua",
    "song21": "Tukur tukur dekhte ho kya, tukur tukur dekhte ho kya",
    "song22": "Aaj phir tum pe pyaar aaya hai, behad aur beshumar aaya hai",
    "song23": "Hawaon se tera pata poochta hoon, ab toh aaja tu kahin se",
    "song24": "Tere mere beech mein kya hai, yeh question hai answer hai",
    "song25": "Dil diyan gallan, karange naal naal beh ke",
    "song26": "Sanam re, sanam re, tu mera sanam hua re",
    "song27": "Main hoon hero tera, main hoon hero tera",
    "song28": "Bhula dena mujhe hai alvida tujhe",
    "song29": "Maiyya yashoda, yeh tera kanhaiya",
    "song30": "Lae dooba, lae dooba, lae dooba re",
    "song31": "Nazm nazm sa mere, hothon pe thehar ja",
    "song32": "Jab tak tujhe pyaar se, beinteha main bhar na doon",
    "song33": "Koi bhi nahi hai mera, sath chhod doon yaar",
    "song34": "Pal bhar thahar jaao, dil ye sambhal jaaye",
    "song35": "Tere bina guzara, ae dil hai mushkil",
    "song36": "Mere rashke qamar, tune pehli nazar",
    "song37": "Dheere dheere se meri zindagi mein aana",
    "song38": "Jee karda, main tenu vekhi jawan",
    "song39": "Gulabi aankhen jo teri dekhi, sharabi ye dil ho gaya",
    "song40": "Kaun tujhe yun pyaar karega, jaise main karti hoon",
    "song41": "Kar har maidaan fateh, o bandeya",
    "song42": "Hasi ban gaye female version, hum tere bin ab reh nahi sakte",
    "song43": "Tera ban jaunga, main tera ban jaunga",
    "song44": "Bekhayali mein bhi tera hi khayal aaye",
    "song45": "Dilbaro, bapu tere karke duniya bhula doon main",
    "song46": "Kabira maan ja, kabira maan ja",
    "song47": "Duniya mein kitni hai nafratein, phir bhi dilo mein hai chahatein",
    "song48": "Raabta kehte hain khuda ne, tujhe mere liye raabta kiya",
    "song49": "Tum jo mile, bhar aaya kyun",
    "song50": "Zehnaseeb, zehnaseeb tujhe chaahun betahasha zehnaseeb",
    "song51": "Ae mere humsafar, ek zara intezaar",
    "song52": "Mitti di khushboo, aayi, kya rooh bhi meri khushboo khayi",
    "song53": "Teri ore, teri ore, teri ore hai rabba",
    "song54": "Jag ghoomeya, thare jaisa na koi",
    "song55": "Tere sang yaara, khush rang bahara",
    "song56": "Chahun main ya naa, apne tu dil ka pata de",
    "song57": "Janam janam ka saath hai, nibhaane ko saath hai",
    "song58": "Meherbaan hua rab, meherbaan hua rab",
    "song59": "Dil diyan gallan, karange naal naal beh ke",
    "song60": "Sun sathiya mahiya, barsaat bhi aakar chali gayi",
    "song61": "Lamhe ye phir na aaye, tere bina jeena kya",
    "song62": "Hawaon se tera pata poochta hoon, ab toh aaja tu kahin se",
    "song63": "Hasi ban gaye, tum mere
