songs_lyrics = {
    "song1": "Tere bina jeena pade, toh zindagi kya zindagi",
    "song2": "Jeene laga hoon pehle se zyada, pehle se zyada tum pe marne laga hoon",
    "song3": "Sun saathiya mahiya, barsaat bhi aakar chali gayi",
    "song4": "Main phir bhi tumko chahunga, is chahat mein marr jaaunga",
    "song5": "Tum hi ho, ab tum hi ho, zindagi ab tum hi ho",
    "song6": "Aaj se teri saari galiyan meri ho gayi",
    "song7": "Tum jo aaye zindagi mein baat ban gayi",
    "song8": "Channa mereya mereya, channa mereya mereya",
    "song9": "Tere sang yaara, khush rang bahara",
    "song10": "Janam janam ka saath hai, nibhaane ko saath hai",
    "song11": "Raabta, kehte hain khuda ne",
    "song12": "Nazdeekiyan, mil ke yeh bhi woh bhi",
    "song13": "Sab tera, sab tera, sab tera phoolon se jyada phoolon se bhara",
    "song14": "Muskurane ki wajah tum ho, gungunane ki wajah tum ho",
    "song15": "Bolna mahi bolna, tere liye aaya main toh",
    "song16": "Tum mile toh lamhe tham gaye, tum mile toh saare karam",
    "song17": "Hasi ban gaye, tum mere aasmaan",
    "song18": "Kar gayi chull, mat kar itna ullu",
    "song19": "Zara sa, zara sa khwabon mein roz aao",
    "song20": "Gerua, rang de tu mohe gerua",
    "song21": "Tukur tukur dekhte ho kya, tukur tukur dekhte ho kya",
    "song22": "Aaj phir tum pe pyaar aaya hai, behad aur beshumar aaya hai",
    "song23": "Hawaon se tera pata poochta hoon, ab toh aaja tu kahin se",
    "song24": "Tere bina adhoori hai ye raatein, tum mere liye sab kuch ho",
    "song25": "Mohabbat ki raahon mein aahista aahista kho jayein hum",
    "song26": "Aaj se teri saari galiyan meri ho gayi",
    "song27": "Tum jo aaye zindagi mein baat ban gayi",
    "song28": "Channa mereya mereya, channa mereya mereya",
    "song29": "Tere sang yaara, khush rang bahara",
    "song30": "Janam janam ka saath hai, nibhaane ko saath hai",
    "song31": "Raabta, kehte hain khuda ne",
    "song32": "Nazdeekiyan, mil ke yeh bhi woh bhi",
    "song33": "Sab tera, sab tera, sab tera phoolon se jyada phoolon se bhara",
    "song34": "Muskurane ki wajah tum ho, gungunane ki wajah tum ho",
    "song35": "Bolna mahi bolna, tere liye aaya main toh",
    "song36": "Tum mile toh lamhe tham gaye, tum mile toh saare karam",
    "song37": "Hasi ban gaye, tum mere aasmaan",
    "song38": "Kar gayi chull, mat kar itna ullu",
    "song39": "Zara sa, zara sa khwabon mein roz aao",
    "song40": "Gerua, rang de tu mohe gerua",
    "song41": "Tukur tukur dekhte ho kya, tukur tukur dekhte ho kya",
    "song42": "Aaj phir tum pe pyaar aaya hai, behad aur beshumar aaya hai",
    "song43": "Hawaon se tera pata poochta hoon, ab toh aaja tu kahin se",
    "song44": "Tere bina adhoori hai ye raatein, tum mere liye sab kuch ho",
    "song45": "Mohabbat ki raahon mein aahista aahista kho jayein hum",
    "song46": "Aaj se teri saari galiyan meri ho gayi",
    "song47": "Tum jo aaye zindagi mein baat ban gayi",
    "song48": "Channa mereya mereya, channa mereya mereya",
    "song49": "Tere sang yaara, khush rang bahara",
    "song50": "Janam janam ka saath hai, nibhaane ko saath hai",
    "song51": "Raabta, kehte hain khuda ne",
    "song52": "Nazdeekiyan, mil ke yeh bhi woh bhi",
    "song53": "Sab tera, sab tera, sab tera phoolon se jyada phoolon se bhara",
    "song54": "Muskurane ki wajah tum ho, gungunane ki wajah tum ho",
    "song55": "Bolna mahi bolna, tere liye aaya main toh",
    "song56": "Tum mile toh lamhe tham gaye, tum mile toh saare karam",
    "song57": "Hasi ban gaye, tum mere aasmaan",
    "song58": "Kar gayi chull, mat kar itna ullu",
    "song59": "Zara sa, zara sa khwabon mein roz aao",
    "song60": "Gerua, rang de tu mohe gerua",
    "song61": "Tukur tukur dekhte ho kya, tukur tukur dekhte ho kya",
    "song62": "Aaj phir tum pe pyaar aaya hai, behad aur beshumar aaya hai",
    "song63": "Hawaon se tera pata poochta hoon, ab toh aaja tu kahin se",
    "song64": "Tere bina adhoori hai ye raatein, tum mere liye sab kuch ho",
    "song65": "Mohabbat ki raahon mein aahista aahista kho jayein hum",
    "song66": "Aaj se teri saari galiyan meri ho gayi",
    "song67": "Tum jo aaye zindagi mein baat ban gayi",
    "song68": "Channa mereya mereya, channa mereya mereya",
    "song69": "Tere sang yaara, khush rang bahara",
    "song70": "Janam janam ka saath hai, nibhaane ko saath hai",
}
